version: 2.1

executors:
  tensorflowm-ci:
    docker:
      - image: asteinh/docker:tensorflowm-ci

default-config: &config
  executor: tensorflowm-ci

# FILTERS FOR WORKFLOWS
develop: &develop-filter
  filters:
    branches:
      ignore:
        - master
        - gh-pages
master: &master-filter
  filters:
    branches:
      only: master
deploy: &deploy-filter
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

################################################################################
# JOBS
################################################################################
jobs:
  # BUILD DOCKER IMAGES
  build-images:
    <<: *config
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          cd .. && mkdir -p images
          cp project/.circleci/docker/octave5/Dockerfile .
      - run: |
          export IMAGENAME=tensorflowm-octave5:${CIRCLE_SHA1:0:7}
          docker build -t IMAGENAME .
          docker save --output images/octave5.tar IMAGENAME
      - run: |
          rm Dockerfile
      - persist_to_workspace:
          root: ~/
          paths:
            - images/

  # RUN UNIT TESTS, needs to run on 'machine' to be able to mount repository
  unit-tests:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: |
          docker load --input ../images/octave5.tar
          docker run --rm -v "$PWD:/home/octave" -it octave5
          ls -l
          uname -a
          exit
      - persist_to_workspace:
          root: ~/project/
          paths:
            - tests/*

################################################################################
# WORKFLOWS
################################################################################
workflows:
  version: 2
  # DEVELOPMENT WORKFLOW: BUILD & TEST
  develop:
    jobs:
      - build-images:
          <<: *develop-filter
      - unit-tests:
          requires:
            - build-images
      - build-docs:
          requires:
            - unit-tests
