function [descriptor] = pb_descriptor_tensorflow__OpDef()
%pb_descriptor_tensorflow__OpDef Returns the descriptor for message OpDef.
%   function [descriptor] = pb_descriptor_tensorflow__OpDef()
%
%   See also pb_read_tensorflow__OpDef

  descriptor = struct( ...
    'name', 'OpDef', ...
    'full_name', 'tensorflow.OpDef', ...
    'filename', 'tensorflow/core/framework/op_def.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'name', ...
        'full_name', 'tensorflow.OpDef.name', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'input_arg', ...
        'full_name', 'tensorflow.OpDef.input_arg', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__OpDef__ArgDef(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'output_arg', ...
        'full_name', 'tensorflow.OpDef.output_arg', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__OpDef__ArgDef(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'attr', ...
        'full_name', 'tensorflow.OpDef.attr', ...
        'index', 4, ...
        'number', uint32(4), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__OpDef__AttrDef(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'summary', ...
        'full_name', 'tensorflow.OpDef.summary', ...
        'index', 5, ...
        'number', uint32(5), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'description', ...
        'full_name', 'tensorflow.OpDef.description', ...
        'index', 6, ...
        'number', uint32(6), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'deprecation', ...
        'full_name', 'tensorflow.OpDef.deprecation', ...
        'index', 7, ...
        'number', uint32(8), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__OpDeprecation(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'is_aggregate', ...
        'full_name', 'tensorflow.OpDef.is_aggregate', ...
        'index', 8, ...
        'number', uint32(16), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'is_stateful', ...
        'full_name', 'tensorflow.OpDef.is_stateful', ...
        'index', 9, ...
        'number', uint32(17), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'is_commutative', ...
        'full_name', 'tensorflow.OpDef.is_commutative', ...
        'index', 10, ...
        'number', uint32(18), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'allows_uninitialized_input', ...
        'full_name', 'tensorflow.OpDef.allows_uninitialized_input', ...
        'index', 11, ...
        'number', uint32(19), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'control_output', ...
        'full_name', 'tensorflow.OpDef.control_output', ...
        'index', 12, ...
        'number', uint32(20), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', char([]), ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  put(descriptor.field_indeces_by_number, uint32(4), 4);
  put(descriptor.field_indeces_by_number, uint32(5), 5);
  put(descriptor.field_indeces_by_number, uint32(6), 6);
  put(descriptor.field_indeces_by_number, uint32(8), 7);
  put(descriptor.field_indeces_by_number, uint32(16), 8);
  put(descriptor.field_indeces_by_number, uint32(17), 9);
  put(descriptor.field_indeces_by_number, uint32(18), 10);
  put(descriptor.field_indeces_by_number, uint32(19), 11);
  put(descriptor.field_indeces_by_number, uint32(20), 12);

