function [descriptor] = pb_descriptor_tensorflow__TensorShapeProto__Dim()
%pb_descriptor_tensorflow__TensorShapeProto__Dim Returns the descriptor for message Dim.
%   function [descriptor] = pb_descriptor_tensorflow__TensorShapeProto__Dim()
%
%   See also pb_read_tensorflow__TensorShapeProto__Dim

  descriptor = struct( ...
    'name', 'Dim', ...
    'full_name', 'tensorflow.TensorShapeProto.Dim', ...
    'filename', 'tensorflow/core/framework/tensor_shape.proto', ...
    'containing_type', 'tensorflow.TensorShapeProto', ...
    'fields', [ ...
      struct( ...
        'name', 'size', ...
        'full_name', 'tensorflow.TensorShapeProto.Dim.size', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(3), ...
        'matlab_type', uint32(2), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int64(0), ...
        'read_function', @(x) typecast(x, 'int64'), ...
        'write_function', @(x) typecast(int64(x), 'uint64'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'name', ...
        'full_name', 'tensorflow.TensorShapeProto.Dim.name', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = javaObject('java.util.HashMap');
  javaMethod('put', descriptor.field_indeces_by_number, uint32(1), 1);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(2), 2);

