function [descriptor] = pb_descriptor_tensorflow__OpDef__AttrDef()
%pb_descriptor_tensorflow__OpDef__AttrDef Returns the descriptor for message AttrDef.
%   function [descriptor] = pb_descriptor_tensorflow__OpDef__AttrDef()
%
%   See also pb_read_tensorflow__OpDef__AttrDef

  descriptor = struct( ...
    'name', 'AttrDef', ...
    'full_name', 'tensorflow.OpDef.AttrDef', ...
    'filename', 'tensorflow/core/framework/op_def.proto', ...
    'containing_type', 'tensorflow.OpDef', ...
    'fields', [ ...
      struct( ...
        'name', 'name', ...
        'full_name', 'tensorflow.OpDef.AttrDef.name', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'type', ...
        'full_name', 'tensorflow.OpDef.AttrDef.type', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'default_value', ...
        'full_name', 'tensorflow.OpDef.AttrDef.default_value', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__AttrValue(x{1}, x{2}, x{3}), ...
        'write_function', @(x) util.protobuf.lib.pblib_generic_serialize_to_string(x), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'description', ...
        'full_name', 'tensorflow.OpDef.AttrDef.description', ...
        'index', 4, ...
        'number', uint32(4), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'has_minimum', ...
        'full_name', 'tensorflow.OpDef.AttrDef.has_minimum', ...
        'index', 5, ...
        'number', uint32(5), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) util.protobuf.lib.pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'minimum', ...
        'full_name', 'tensorflow.OpDef.AttrDef.minimum', ...
        'index', 6, ...
        'number', uint32(6), ...
        'type', uint32(3), ...
        'matlab_type', uint32(2), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', int64(0), ...
        'read_function', @(x) typecast(x, 'int64'), ...
        'write_function', @(x) typecast(int64(x), 'uint64'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'allowed_values', ...
        'full_name', 'tensorflow.OpDef.AttrDef.allowed_values', ...
        'index', 7, ...
        'number', uint32(7), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__AttrValue(x{1}, x{2}, x{3}), ...
        'write_function', @(x) util.protobuf.lib.pblib_generic_serialize_to_string(x), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = javaObject('java.util.HashMap');
  javaMethod('put', descriptor.field_indeces_by_number, uint32(1), 1);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(2), 2);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(3), 3);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(4), 4);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(5), 5);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(6), 6);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(7), 7);
