function [descriptor] = pb_descriptor_tensorflow__NameAttrList()
%pb_descriptor_tensorflow__NameAttrList Returns the descriptor for message NameAttrList.
%   function [descriptor] = pb_descriptor_tensorflow__NameAttrList()
%
%   See also pb_read_tensorflow__NameAttrList

  descriptor = struct( ...
    'name', 'NameAttrList', ...
    'full_name', 'tensorflow.NameAttrList', ...
    'filename', 'tensorflow/core/framework/attr_value.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'name', ...
        'full_name', 'tensorflow.NameAttrList.name', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'attr', ...
        'full_name', 'tensorflow.NameAttrList.attr', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) pb_read_tensorflow__NameAttrList__AttrEntry(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);

