function [descriptor] = pb_descriptor_tensorflow__VariantTensorDataProto()
%pb_descriptor_tensorflow__VariantTensorDataProto Returns the descriptor for message VariantTensorDataProto.
%   function [descriptor] = pb_descriptor_tensorflow__VariantTensorDataProto()
%
%   See also pb_read_tensorflow__VariantTensorDataProto

  descriptor = struct( ...
    'name', 'VariantTensorDataProto', ...
    'full_name', 'tensorflow.VariantTensorDataProto', ...
    'filename', 'tensorflow/core/framework/tensor.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'type_name', ...
        'full_name', 'tensorflow.VariantTensorDataProto.type_name', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'metadata', ...
        'full_name', 'tensorflow.VariantTensorDataProto.metadata', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(12), ...
        'matlab_type', uint32(8), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', uint8(''), ...
        'read_function', @(x) uint8(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'tensors', ...
        'full_name', 'tensorflow.VariantTensorDataProto.tensors', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__TensorProto(x{1}, x{2}, x{3}), ...
        'write_function', @pblib_generic_serialize_to_string, ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);

