function [descriptor] = pb_descriptor_tensorflow__TensorShapeProto()
%pb_descriptor_tensorflow__TensorShapeProto Returns the descriptor for message TensorShapeProto.
%   function [descriptor] = pb_descriptor_tensorflow__TensorShapeProto()
%
%   See also pb_read_tensorflow__TensorShapeProto

  descriptor = struct( ...
    'name', 'TensorShapeProto', ...
    'full_name', 'tensorflow.TensorShapeProto', ...
    'filename', 'tensorflow/core/framework/tensor_shape.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'dim', ...
        'full_name', 'tensorflow.TensorShapeProto.dim', ...
        'index', 1, ...
        'number', uint32(2), ...
        'type', uint32(11), ...
        'matlab_type', uint32(9), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', struct([]), ...
        'read_function', @(x) util.protobuf.parser.pb_read_tensorflow__TensorShapeProto__Dim(x{1}, x{2}, x{3}), ...
        'write_function', @(x) util.protobuf.lib.pblib_generic_serialize_to_string(x), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'unknown_rank', ...
        'full_name', 'tensorflow.TensorShapeProto.unknown_rank', ...
        'index', 2, ...
        'number', uint32(3), ...
        'type', uint32(8), ...
        'matlab_type', uint32(3), ...
        'wire_type', uint32(0), ...
        'label', uint32(1), ...
        'default_value', uint32(0), ...
        'read_function', @(x) util.protobuf.lib.pblib_helpers_first(typecast(x, 'uint32')), ...
        'write_function', @(x) typecast(uint32(x), 'uint32'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = javaObject('java.util.HashMap');
  javaMethod('put', descriptor.field_indeces_by_number, uint32(2), 1);
  javaMethod('put', descriptor.field_indeces_by_number, uint32(3), 2);
